// <auto-generated />
using System;
using AdministracaoContas.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdministracaoContas.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20211010235508_FormaPagemento")]
    partial class FormaPagemento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdministracaoContas.Business.Models.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodigoFormaPagamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiaPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Loja")
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Parcela")
                        .HasColumnType("int");

                    b.Property<string>("Produto")
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoFormaPagamento")
                        .IsUnique();

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.DespesaParcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDespesa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Parcela")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdDespesa");

                    b.ToTable("DespesasParcela");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Sigla")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Codigo");

                    b.ToTable("FormaPamento");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.Despesa", b =>
                {
                    b.HasOne("AdministracaoContas.Business.Models.FormaPagamento", "FormaPagamento")
                        .WithOne("Despesa")
                        .HasForeignKey("AdministracaoContas.Business.Models.Despesa", "CodigoFormaPagamento")
                        .IsRequired();

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.DespesaParcela", b =>
                {
                    b.HasOne("AdministracaoContas.Business.Models.Despesa", "Despesa")
                        .WithMany("DespesaParcela")
                        .HasForeignKey("IdDespesa")
                        .IsRequired();

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.Despesa", b =>
                {
                    b.Navigation("DespesaParcela");
                });

            modelBuilder.Entity("AdministracaoContas.Business.Models.FormaPagamento", b =>
                {
                    b.Navigation("Despesa");
                });
#pragma warning restore 612, 618
        }
    }
}
